Remote markers/targets fetch
Novatics/skvngr pull request #1
Opened 2018-12-27 18:12 UTC by milovaz

- Added an AssetLoader class to load remote assets from skvngr-server 
- Dynamically mounting Viro configuration tags (mainly the markers and targets tags)

2018-12-27 18:16 UTC, Yurickh commented on js/HelloWorldSceneAR.js
> +    this.setState({ markers });
This whole function can be a map over targets, don't you agree?

2018-12-27 18:18 UTC, Yurickh commented on js/HelloWorldSceneAR.js
> +    this.assetLoader = new AssetLoader('https://skvngr-server.herokuapp.com');
You don't need to put it into the constructor. You can just use class properties here.

```suggestion
  assetLoader = new AssetLoader('https://skvngr-server.herokuapp.com');
```

2018-12-27 18:23 UTC, Yurickh requested changes

2018-12-27 18:23 UTC, Yurickh commented on js/HelloWorldSceneAR.js
> +        {this.state.markers}
Instead of loading the elements onto the state, we can leave only the targets there and map over them to render the elements here.

2018-12-27 18:23 UTC, Yurickh commented on js/AssetLoader.js
> +    const targets = {};
What's the advantage of storing them in an object, as opposed to an array?

2018-12-27 18:26 UTC, milovaz commented on js/HelloWorldSceneAR.js
> +    this.setState({ markers });
I created it as function because some other loads/transformations will be implemented on ViroARImageMarker generation. I thought it would be a bit confusing to place everything in a map.

2018-12-27 18:28 UTC, Yurickh commented on js/HelloWorldSceneAR.js
> +    this.setState({ markers });
You can load the ViroARIMageMarker here and store the targets into state so they can be mapped into render.

2018-12-27 18:45 UTC, Yurickh commented on js/AssetLoader.js
> +    const targets = {};
It's because ViroARIMageMarker expects an object as parameter. Resolved.

2018-12-28 11:26 UTC, Yurickh approved these changes
The API is clean and the code is direct to the point, congrats! 👏

2018-12-28 11:58 UTC, Yurickh requested changes
We can approve it as soon as the conflicts are resolved

2018-12-28 14:39 UTC, Yurickh approved these changes
🌮

2018-12-28 16:29 UTC, merged